name: e_pack
description: A storage and delivery site
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Functional Programming
  dartz: ^0.10.0

  # Equatable Objects
  equatable: ^2.0.3

  # Caching
  shared_preferences: any

  # Masked Text
  extended_masked_text: ^2.3.1

  # Password Validator
  flutter_pw_validator: ^1.2.1

  # Internet Checker
  internet_connection_checker: ^0.0.1+3

  # State Management
  provider: ^6.0.1

  # Bloc State Management
  flutter_bloc: ^8.0.1

  # HTTP Requests
  http: ^0.13.4
  dio: ^4.0.4

  # DateTime Picker Widget
  syncfusion_flutter_datepicker: ^19.2.62


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
