name: e_pack
description: The E-Pack Service Application

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  appwrite: ^2.0.2

  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  equatable: ^2.0.3
  extended_masked_text: ^2.3.1
  flutter:
    sdk: flutter
  flutter_pw_validator: ^1.2.1
  internet_connection_checker: ^0.0.1+3
  provider: ^6.0.1
  http: ^0.13.4
  dio: ^4.0.4
  syncfusion_flutter_datepicker: ^19.2.62

dev_dependencies:
  build_runner: ^2.1.5
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  
  mockito: ^5.0.16

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
