// Mocks generated by Mockito 5.0.16 from annotations
// in e_pack/test/delivery_request/domain/use_cases/send_delivery_request_test.dart.
// Do not manually edit this file.

import 'package:e_pack/features/delivery_option/domain/repositories/delivery_request_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [DeliveryRequestRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeliveryRequestRepository extends _i1.Mock
    implements _i2.DeliveryRequestRepository {
  MockDeliveryRequestRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String toString() => super.toString();
}
