// Mocks generated by Mockito 5.0.16 from annotations
// in e_pack/test/features/requestBuilder/domain/usecases/send_user_request_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUserRequest_0 extends _i1.Fake implements _i2.UserRequest {}

/// A class which mocks [UserRequestRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRequestRepository extends _i1.Mock
    implements _i3.UserRequestRepository {
  MockUserRequestRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRequest get request =>
      (super.noSuchMethod(Invocation.getter(#request),
          returnValue: _FakeUserRequest_0()) as _i2.UserRequest);
  @override
  String toString() => super.toString();
}
